echo "+ we assume you already have an ssh server running in your container"
echo "+ try something like this"
echo "+ ssh <user>@<container-name.docker> <port>"
echo "+ e.g.:"
echo "ssh student@reslocal/ubuntu-base:latest.docker 22"
